### ISSUE TITLE
$$...$$ 不支持跨行

### ISSUE THREAD

**Issue by yfwz100** [fuchen/hexo-static-math#1]
如题，目前用的正则表达式来替换的话，不支持 $$ ... $$ 内部换行的情况。

**Comment by fuchen** [comment]
`` `$$ ... $$` `` 和 `` `$ ... $` `` 不支持换行，主要有两个考虑：
1. 它们起的作用是 shortcut，为的是方便书写简单的表达式，只支持单行就够了。
2. 与原生 markdown 兼容性的考虑。`` `...` ``在 markdown 里是用来书写单行代码。如果中间有换行，在 markdown 编辑器里的 preview 会很奇怪。

如果需要换行，就要用`{% math %}`。

**Comment by yfwz100** [comment]
我不同意你的说法，$...$ 不支持跨行可以理解，但是 $$ ... $$ 生成的是 block level 的表达式。从现实上看， $$ ... $$ 的表达式看起来会更复杂一点；另一点是从生成结果上的一致性看，在源文本上也应该支持跨行。用 Typora 等编辑器生成的 block level 的表达式的时候，也是跨行的。

**Comment by fuchen** [comment]
我纠正一点，用来标识表达式的是`` `$$ ... $$` ``，而不是`$$ ... $$`。既然你还有疑问，我就再详细说下吧。

在 filter 里用正则表达式替换来扩展内容，这种方式实际上是有缺陷的，跟 markdown 并不能无缝兼容。比如这段文本：`` `$=require('jquery'); vue.jquery=$` ``，意图应该是段 js 代码，实际上却会被插件误判为数学表达式。如果直接使用 `$...$` 或者 `$$...$$`  来标识表达式，那么误判的情况会更多。比如：`笔记本$1000，手机$400`

在 hexo 里扩展自定义内容，最稳妥的方式是通过 tag，即类似 `{% math %} .. {% endmath %}`这种方式。

filter 通常可以比 tag 少敲几个字符，所以我同时实现了 filter 和 tag，但要满足以下条件：
1. 最最重要的：**如果 filter 会破坏 markdown 格式，那么破坏力必须很有限。** 比如`` `$$ ... $$` ``的破坏力就比`$$ ... $$`小许多。单行正则替换的破坏力也会比多行替换的破坏力小很多。单行如果误识别，你一眼能看出哪里出问题了，但如果是多行，错误原因就不那么直观了。尤其是当插件使用者不清楚 hexo 实现机制的时候，可能就无法排错。
2. 尽量不去破坏 markdown 的preview。`` `...` `` 只支持单行代码，如果中间有换行，preview 就惨不忍睹了。你可以在本页面的回复框里试一试看 `` `...` `` 里插入多行文本会是什么景象。
3. filter 必须比 tag 更快捷。前两个问题，通过增加 filter 的复杂度，都可以一定程度上减轻。但如果 filter 不能帮我们节约几次按键，为什么不直接使用 tag 呢？

我会更新下readme，但不会在 filter 里支持多行表达式。谢谢！

**Comment by yfwz100** [comment]
好吧，我使用 markdown-it 以及其 mathjax 插件了。你说的情况确实有可能，但是我的使用场景更多是写 mathjax 而不是写美元符号。我一开始修改了你的插件，但是发现局限性还是很大。谢谢您的工作。
